### ISSUE TITLE
Anaconda package

### ISSUE THREAD

**Issue by AntoineD** [rlgomes/delta#8]
Hello,
is it OK for you if I add your package to conda-forge?
I can create the anaconda recipe and set myself, or just you or both of us as the recipe maintainers. Just let me know.

**Comment by rlgomes** [comment]
I've never done anything anaconda related... feel free to create the PR and I can make you a contributer to this repo if that makes it easier to hook up any external things.

**Comment by AntoineD** [comment]
I've just accepted your invitation but I actually do not need push access to you repo: a conda-forge anaconda recipe (just the recipe, no package sources is needed there) lives in its own repo that will, in the end, be hosted in the conda-forge gh account.
I mentioned the [recipe maintainership](https://conda-forge.org/docs/maintainer/adding_pkgs.html#maintainer-role) because the question arises if I create the recipe while not being the maintainer of delta.

**Comment by AntoineD** [comment]
The PR for the conda forge anaconda recipe is [here](https://github.com/conda-forge/staged-recipes/pull/11795), now we just have to wait for the reviewers.

**Comment by AntoineD** [comment]
Hello,
the package is now available from conda-forge, the recipe repo is [here](https://github.com/conda-forge/delta-feedstock).
I will watch your repo and update the recipe when needed.
Thanks for your package!
